include("test-slope.jl")
include("test-stat_quantile.jl")
include("test-stat_linreg.jl")
include("test-stat_apply.jl")
include("test-movmean.jl")
include("test-approx.jl")
include("test-nan_func.jl")
